import os


MAIL_ADDRESS = os.environ['MAIL_ADDRESS']
PASSWORD = os.environ['PASSWORD']
HOME_URL = os.environ['HOME_URL']
LOGIN_URL = os.environ['LOGIN_URL']
DISCOUNT_URL = os.environ['DISCOUNT_URL']
GUIDE_URL = os.environ['GUIDE_URL']
XPATH_AFTER_DISCOUNT_PRICE = os.environ['XPATH_AFTER_DISCOUNT_PRICE']
XPATH_BEFORE_DISCOUNT_PRICE = os.environ['XPATH_BEFORE_DISCOUNT_PRICE']
XPATH_AFFILIATE_LINK = os.environ['XPATH_AFFILIATE_LINK']
XPATH_TITLE = os.environ['XPATH_TITLE']
XPATH_ACCOUNT = os.environ['XPATH_ACCOUNT']
XPATH_LOGOUT = os.environ['XPATH_LOGOUT']
SEARCH_WORD = os.environ['SEARCH_WORD']
CONSUMER_KEY = os.environ['CONSUMER_KEY']
CONSUMER_SECRET = os.environ['CONSUMER_SECRET']
ACCESS_TOKEN_KEY = os.environ['ACCESS_TOKEN_KEY']
ACCESS_TOKEN_SECRET = os.environ['ACCESS_TOKEN_SECRET']

LINE_NOTIFY_API_URL = os.environ['LINE_NOTIFY_API_URL']
LINE_NOTIFY_TOKEN = os.environ['LINE_NOTIFY_TOKEN']